<?php $title = 'Mechanical'; include 'header.php'; ?>
<style>
*{
  font-size: 18px;
}
</style>
<section class="about-head">
    <div class="container-fluid">
        <div class="about-title">
            <h1>Mechanical</h1>
        </div>
    </div>
</section>

<section class="about-section3">
    <div class="container">
        <div class="row">
            <!-- <div class="col-sm-12 col-md-3 col-md-push-9">
                <br><br><br>
                <img src="images/MechSS.png" class="img-responsive"><center>The Pratham Satellite</center>
            </div>
            <div class="col-sm-12 col-md-9 col-md-pull-3"> -->
                <div class="section3-content">
                <p align="justify">The <b>Mechanical Subsystem</b> consists of three segments: <b>Structures, Thermals and Integration</b>. The broad function of this subsystem is to design the body of the satellite and mount all components on it, shielding them well from shock, excessive temperatures, radiations and stray magnetic fields. It manages control of the internal thermal environment at all times and designs mechanisms crucial to the working of components.</p>

                        <p align="justify">This subsystem does the following tasks - <br>
                        <ol style="font-size:18px";>
                        <li>Choose the optimal <b>shape, material and framework</b> for the satellite body by simulating loading conditions during launch and in orbit
                        <li>Communicate <b>weight and dimension</b> constraints to other subsystems
                        <li>Provide means of <b>mounting, fastening and cushioning</b> all components securely 
                        <li>Dissipate excess heat generated by the components, maintain <b>steady temperature</b> conditions within the satellite and protect the components from the harsh space environment
                        <li>Provide <b>routing</b> for the various power and data cables used
                        <li><b>Interface</b> the satellite to the launch vehicle
                        <li><b>Fabricate</b> the final flight model of the satellite and test it for resistance to shocks and thermal vacuum conditions
</p>
                </div>
            </div>
        </div>
    </div>
</section>

<?php include 'footer.php'; ?>